// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdpKLVGHGL_GHfXncyCRbb0LGF9zckwX0',
    appId: '1:447008788763:web:1ed5b2fc8836000ada03be',
    messagingSenderId: '447008788763',
    projectId: 'chatapp-428a3',
    authDomain: 'chatapp-428a3.firebaseapp.com',
    storageBucket: 'chatapp-428a3.appspot.com',
    measurementId: 'G-RBJEKS8YJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_veePE9wJnfEzNQyGg-yKXPd9bZFQI-U',
    appId: '1:447008788763:android:c327652979bcf4e7da03be',
    messagingSenderId: '447008788763',
    projectId: 'chatapp-428a3',
    storageBucket: 'chatapp-428a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMw7-lt1EB-Dhv-TCx_uJuU-TJKY-pnjE',
    appId: '1:447008788763:ios:3d28c4190aae64fcda03be',
    messagingSenderId: '447008788763',
    projectId: 'chatapp-428a3',
    storageBucket: 'chatapp-428a3.appspot.com',
    iosClientId: '447008788763-q7mgjpg4jiscrdv1k3jl9idr68vu1rd6.apps.googleusercontent.com',
    iosBundleId: 'com.Jamesleonard.chatapp',
  );
}
